// 100+ unique spectrum card pairs for Wavelength
const SPECTRUM_CARDS = [
  ["Hot", "Cold"],
  ["Overrated", "Underrated"],
  ["Good", "Evil"],
  ["Round", "Pointy"],
  ["Hipster", "Mainstream"],
  ["Tastes Good", "Tastes Bad"],
  ["Dangerous", "Safe"],
  ["Rare", "Common"],
  ["Old", "Young"],
  ["Loud", "Quiet"],
  ["Dry", "Wet"],
  ["Fast", "Slow"],
  ["Heavy", "Light"],
  ["Hard", "Soft"],
  ["Dark", "Bright"],
  ["Sweet", "Sour"],
  ["Expensive", "Cheap"],
  ["Big", "Small"],
  ["Clean", "Dirty"],
  ["Beautiful", "Ugly"],
  ["Healthy", "Unhealthy"],
  ["Scary", "Cute"],
  ["Smart", "Dumb"],
  ["Famous", "Unknown"],
  ["Boring", "Exciting"],
  ["Simple", "Complicated"],
  ["Strong", "Weak"],
  ["Modern", "Ancient"],
  ["Natural", "Artificial"],
  ["Useful", "Useless"],
  ["Relaxing", "Stressful"],
  ["Loved", "Hated"],
  ["Easy", "Difficult"],
  ["Smooth", "Rough"],
  ["Fresh", "Stale"],
  ["Funny", "Serious"],
  ["Rich", "Poor"],
  ["Fragile", "Sturdy"],
  ["Innocent", "Guilty"],
  ["Brave", "Cowardly"],
  ["Tall", "Short"],
  ["Thick", "Thin"],
  ["Wet", "Dry"],
  ["Wild", "Tame"],
  ["Fancy", "Plain"],
  ["Warm", "Cool"],
  ["Deep", "Shallow"],
  ["Tight", "Loose"],
  ["Bitter", "Sweet"],
  ["Spicy", "Mild"],
  ["Noisy", "Silent"],
  ["Messy", "Tidy"],
  ["Formal", "Casual"],
  ["Genius", "Foolish"],
  ["Powerful", "Helpless"],
  ["Chaotic", "Orderly"],
  ["Mysterious", "Obvious"],
  ["Addictive", "Forgettable"],
  ["Romantic", "Unromantic"],
  ["Trendy", "Outdated"],
  ["Satisfying", "Frustrating"],
  ["Peaceful", "Violent"],
  ["Loyal", "Treacherous"],
  ["Generous", "Greedy"],
  ["Patient", "Impatient"],
  ["Humble", "Arrogant"],
  ["Honest", "Dishonest"],
  ["Optimistic", "Pessimistic"],
  ["Creative", "Unimaginative"],
  ["Polite", "Rude"],
  ["Flexible", "Rigid"],
  ["Reliable", "Unreliable"],
  ["Energetic", "Lazy"],
  ["Graceful", "Clumsy"],
  ["Mature", "Immature"],
  ["Realistic", "Fantasy"],
  ["Necessary", "Unnecessary"],
  ["Legal", "Illegal"],
  ["Moral", "Immoral"],
  ["Logical", "Illogical"],
  ["Delicious", "Disgusting"],
  ["Comfortable", "Uncomfortable"],
  ["Permanent", "Temporary"],
  ["Visible", "Invisible"],
  ["Ordinary", "Extraordinary"],
  ["Predictable", "Unpredictable"],
  ["Transparent", "Opaque"],
  ["Wholesome", "Unwholesome"],
  ["Mainstream", "Niche"],
  ["Overused", "Underused"],
  ["Timeless", "Dated"],
  ["Crunchy", "Chewy"],
  ["Savory", "Sweet"],
  ["Athletic", "Unathletic"],
  ["Introverted", "Extroverted"],
  ["Nerdy", "Cool"],
  ["Rebellious", "Obedient"],
  ["Artistic", "Scientific"],
  ["Urban", "Rural"],
  ["Futuristic", "Retro"],
  ["Emotional", "Rational"],
  ["Masculine", "Feminine"],
  ["Minimalist", "Maximalist"],
  ["Overachiever", "Underachiever"],
  ["Sandwich", "Not a Sandwich"],
  ["A Snack", "A Meal"],
  ["A Sport", "Not a Sport"],
  ["Art", "Not Art"],
  ["Wizard", "Not a Wizard"],
  ["Hero", "Villain"],
  ["Pet Material", "Not Pet Material"],
  ["Breakfast Food", "Dinner Food"],
  ["Indoor Activity", "Outdoor Activity"],
  ["Kid Friendly", "Adults Only"],
  ["Guilty Pleasure", "Openly Enjoyed"],
  ["Underappreciated", "Overappreciated"],
  ["Instagrammable", "Not Instagrammable"],
  ["Worth the Hype", "Not Worth the Hype"],
  ["Childhood", "Adulthood"],
  ["First Date", "Married Life"],
  ["Easy to Learn", "Hard to Master"],
  ["Needs Salt", "Has Enough Salt"],
  ["Would Survive Horror Movie", "Would Die First"],
  ["Good Superpower", "Bad Superpower"],
  ["Monday Energy", "Friday Energy"],
  ["Brain Food", "Comfort Food"],
  ["Mountain", "Beach"],
  ["Cat Person", "Dog Person"],
  ["Movie", "Book"],
  ["Morning Person", "Night Owl"],
];

function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

function getShuffledCards() {
  return shuffleArray(SPECTRUM_CARDS);
}

module.exports = { SPECTRUM_CARDS, getShuffledCards };
